### PR TITLE
docs(samples): move automl samples to nodejs-automl

### LINKED ISSUE #305: Move automl samples to googleapis/nodejs-automl
See similar issue for nodejs-translate, for moving the AutoML samples from this repo into the nodejs-automl repo's samples directory

https://github.com/googleapis/nodejs-translate/issues/200

Essentially, the request is:

`mv googleapis/nodejs-vision/samples/automl googleapis/nodejs-automl/samples/vision`

### PR DESCRIPTION
**Pull request by jkwlui**
Closes #305 

Moved to nodejs-automl. See https://github.com/googleapis/nodejs-automl/pull/134/files

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Is there an equivalent PR adding these to automl?  could you reference it here?

**Review by stephenplusplus — APPROVED** [review]

**Comment by JustinBeckwith** [comment]
@jkwlui please work with @beccasaurus and @googleapis/ml-apis to make sure we coordinate the update of any links in the cloud.google.com documentation.

**Review by JustinBeckwith — CHANGES_REQUESTED** [review]
Making sure we have an ack from @beccasaurus on the c.g.c links first :)

**Comment by beccasaurus** [comment]
This'll be blocked pending the merge into nodejs-automl, so we can update the doc links and republish :)  Thank you for making the change!!

**Comment by JustinBeckwith** [comment]
https://github.com/googleapis/nodejs-automl/pull/134 is merged, so I am gonna land this

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
