### PR TITLE
Fixed the failing unit test.

### PR DESCRIPTION
**Pull request by happyhuman**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Thanks! It fixes the pdf test, but another one still fails for me:

  ✖ detect › should detect similar web images in a local file

```
  output.includes(URL: https://cloud.google.com/vision/docs/images/)
  => false
```

Could you please take a look at that test as well? Thanks!

**Comment by happyhuman** [comment]
@alexander-fenster I can look into the other one. But I did not work on the "similar web images" code, and I am not sure why this one is failing. So, it will take me a bit longer to figure it out and fix it. Do you happen to know who implemented that sample?
I am looking at the failed test anyway.

**Comment by happyhuman** [comment]
Okay, I found it. The reason for the web-image related tests fail is the following assertion:
t.true(output.includes('URL: https://cloud.google.com/vision/docs/images/'));

But when I look at the console output, I noticed that the following line in the output sometimes is printed, but not every time:
  URL: https://cloud.google.com/vision/docs/images/faulkner.jpg?hl=ja

This of course makes the unit test to fail sometimes. I just played with the code a little, so I don't know the code well enough to know why this line is not printed all the time. but a quick fix is to disable/remove the above assertion. @alexander-fenster What is your suggestion here?

**Comment by alexander-fenster** [comment]
I'm not the one who makes decision here - I only can assert that I need 100% samples tests pass to release the package via our continuous integration system, but your question should be answered by other folks - @ace-n @jmdobry @remi what do you think? Seems the `v1` API results for `should detect similar web images in a local file` are flaky enough to fail the test. How do we deal with it?

**Comment by alexander-fenster** [comment]
If you ask me, I would vote for one of the following options (ordered by preference, descending):
- fix the API to always return the same result for the same file
- find some file that produces consistent results for the sample
- disable this test and release the package with test disabled
- release the package as is, just keep running CI until we're lucky enough to have this test passed

**Comment by happyhuman** [comment]
To elaborate a bit, here is one example of the console output which does not contain "URL: https://cloud.google.com/vision/docs/images/" and causing the unit test to fail:

Full matches found: 4
  URL: https://camo.qiitausercontent.com/e009ef102fa0c40d134b1133b138e82b866c06b6/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f37343432382f61613564613435612d366236622d316534322d653238632d3237363832363462653233382e706e67
  Score: 0
  URL: http://tu-easy.com/assest/uploads/d1e2bb66d837daa9e4149ba4506f5884.jpg
  Score: 0
  URL: https://static1.squarespace.com/static/57618e6bb6aa602dea119da4/t/57635378d2b8578a71ee7af7/1466127226526/
  Score: 0
  URL: https://static1.squarespace.com/static/57618e6bb6aa602dea119da4/57619509e707eb1384e33e47/5763531a2994ca8de6eb0bfc/1495126162308/faulkner.jpg?format=500w
  Score: 0
Partial matches found: 4
  URL: https://2.bp.blogspot.com/-9IqLgYRy7wY/Wbswne3H-mI/AAAAAAAAJp0/4oFpMLye3VIFEpsZZxmdb6yI1P-QDmfewCLcBGAs/s1600/011.jpg
  Score: 0
  URL: https://nielchah.com/wp-content/uploads/2016/03/dog-v2.png
  Score: 0
  URL: https://nielchah.com/wp-content/uploads/2016/03/dog-v2-570x350.png
  Score: 0
  URL: https://i.gzn.jp/img/2017/12/31/machine-learning-101/snap10967_m.png
  Score: 0
Web entities found: 10
  Description: Google
  Score: 0.7121000289916992
  Description: 
  Score: 0.7121000289916992
  Description: Google Cloud Platform
  Score: 0.7095999717712402
  Description: Application programming interface
  Score: 0.7041000127792358
  Description: Cloud storage
  Score: 0.5745999813079834
  Description: Google Storage
  Score: 0.5598000288009644
  Description: Knowledge Graph
  Score: 0.5285999774932861
  Description: POST
  Score: 0.5271000266075134
  Description: Google Drive
  Score: 0.5266000032424927
  Description: Google APIs
  Score: 0.520799994468689

**Comment by jmdobry** [comment]
I would modify the test to check for something that's sure to be there.

**Comment by happyhuman** [comment]
The unit test looks for 5 particular strings. The other 4 are reliably found each time. This is the only one that is flaky. In my opinion, we can simply comment out this assertion and still be okay.

**Comment by jmdobry** [comment]
do it

**Comment by happyhuman** [comment]
Done. @alexander-fenster I believe there should not be any more issues.

**Comment by alexander-fenster** [comment]
Looks good to me now, thanks!

**Pull request merged**
