### PR TITLE
feat(samples): add sample of configuring alternate apiEndpoint

### PR DESCRIPTION
**Pull request by bradmiro**
To store reverted changes with setEndpoint samples

### CODE REVIEW

**Comment by bcoe** [comment]
@bradmiro am I to understand we're not to land this yet?

**Comment by bradmiro** [comment]
That's my understanding

**Comment by bcoe** [comment]
@bradmiro I think we're able to move forwards with this again this week?

**Comment by bradmiro** [comment]
I still haven't heard anything on my end, but it's possible you have information that I don't.

**Comment by bradmiro** [comment]
We're good to move forward with this

**Pull request merged**
